[project]
name = "algorithms"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "numpy>=2.2.0",
    "pandas>=2.2.3",
    "pip>=24.3.1",
    "scikit-learn>=1.6.0",
]
